/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas5;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static tugas5.koneksi.koneksiDB;

/**
 *
 * @author ASUS
 */
public class forminput extends javax.swing.JFrame {

    /**
     * Creates new form forminput
     */
    int jumlahh;
    public forminput() {
        initComponents();
        koneksi conn = new koneksi();
        tampildata(); 
        jumlahh = 0;
        jumlah.setText("" + jumlahh);
        tambahjumlah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                jumlahh++;
                jumlah.setText(Integer.toString(jumlahh));
            }
        });
         kurangjumlah.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jumlahh > 0) {
                    jumlahh--;
                    jumlah.setText(Integer.toString(jumlahh));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        tunai = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barang = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        tambahjumlah = new javax.swing.JButton();
        hitungkembali = new javax.swing.JButton();
        hitungtotal = new javax.swing.JButton();
        kurangjumlah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        tabel.setBackground(new java.awt.Color(0, 153, 102));
        tabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabel.setForeground(new java.awt.Color(255, 255, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Barang", "Kode ", "Harga ", "Jumlah beli", "Total harga", "Tunai", "Kembalian"
            }
        ));
        tabel.setEnabled(false);
        tabel.setShowHorizontalLines(true);
        tabel.setShowVerticalLines(true);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1))
        );

        jTabbedPane1.addTab("Riwayat penjualan", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        kode.setEditable(false);
        kode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        jPanel1.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 53, 240, -1));

        harga.setEditable(false);
        harga.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 88, 240, -1));

        jumlah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 117, 97, -1));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 18, 225, -1));

        tunai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(tunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 53, 196, -1));

        kembalian.setEditable(false);
        kembalian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 88, 225, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah beli");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 21, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tunai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 56, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembalian");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 91, -1, -1));

        barang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH BARANG", "KULKAS", "TV", "KIPAS ANGIN", "MICROWAVE", "KOMPUTER" }));
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        jPanel1.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 18, 240, -1));

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 330, -1, -1));

        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 330, -1, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 144, -1, -1));

        tambahjumlah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tambahjumlah.setText("+");
        tambahjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahjumlahActionPerformed(evt);
            }
        });
        jPanel1.add(tambahjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 117, -1, -1));

        hitungkembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungkembali.setText("=");
        hitungkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(hitungkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 53, -1, -1));

        hitungtotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungtotal.setText("Hitung");
        hitungtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungtotalActionPerformed(evt);
            }
        });
        jPanel1.add(hitungtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 117, 79, -1));

        kurangjumlah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kurangjumlah.setText("-");
        jPanel1.add(kurangjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 117, -1, -1));

        tabeltransaksi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Barang", "Kode ", "Harga ", "Jumlah beli", "Total harga", "Tunai", "Kembalian"
            }
        ));
        tabeltransaksi.setEnabled(false);
        tabeltransaksi.setShowHorizontalLines(true);
        tabeltransaksi.setShowVerticalLines(true);
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltransaksi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 179, 577, 139));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gambar3.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 700, 360));

        jTabbedPane1.addTab("Data penjualan", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        
    }//GEN-LAST:event_tabelMouseClicked

    private void hitungkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungkembaliActionPerformed
        // TODO add your handling code here:
        int totalharga1 = Integer.parseInt(total.getText());
        int tunai1 = Integer.parseInt(tunai.getText());
        int kembali = tunai1 - totalharga1;
        if (tunai1 < totalharga1){
            JOptionPane.showMessageDialog(this, "Maaf nominal pembayaran anda kurang");
            tunai.setText("0");
        }else{
        kembalian.setText(Integer.toString(kembali));
        }
    }//GEN-LAST:event_hitungkembaliActionPerformed

    private void tambahjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahjumlahActionPerformed
   
    }//GEN-LAST:event_tambahjumlahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        barang.setSelectedIndex(0);
        kode.setText("");
        harga.setText("");
        jumlahh = 0;
        jumlah.setText(Integer.toString(jumlahh));
        total.setText("");
        tunai.setText("");
        kembalian.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
            java.sql.Connection conn=koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("UPDATE koneksimodul5 SET kode ='"+kode.getText()
                +"', harga='"+harga.getText()+"', jumlah='"+jumlah.getText()
                +"', total ='"+total.getText()+"', tunai='"+tunai.getText()
                +"', kembalian='"+kembalian.getText()+"' WHERE barang='"+barang.getSelectedItem()+"'");
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            tampildata();
        }catch (Exception t){
            System.out.println(t.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try{
            String sql="insert into koneksimodul5 values('"
                    +barang.getSelectedItem()+"','"
                    +kode.getText()+"','"
                    +harga.getText()+"','"
                    +jumlah.getText()+"','"
                    +total.getText()+"','"
                    +tunai.getText()+"','"
                    +kembalian.getText()+"')";
            java.sql.Connection conn=(java.sql.Connection)tugas5.koneksi.koneksiDB();
            java.sql.PreparedStatement 
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampildata();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        String plhmenu = (String)barang.getSelectedItem();
        String kode1;
        String harga1;
        kode1 = "";
        harga1 = "";

        switch(plhmenu){
            case "KULKAS":
            kode1 = "001";
            harga1 = "150000";
            break;
            case "TV":
            kode1 = "002";
            harga1 = "100000";
            break;
            case "KIPAS ANGIN":
            kode1 = "003";
            harga1 = "50000";
            break;
            case "MICROWAVE":
            kode1 = "003";
            harga1 = "50000";
            break;
            case "KOMPUTER":
            kode1 = "003";
            harga1 = "250000";
            break;
        }
        jumlahh = Integer.parseInt(jumlah.getText());
        kode.setText(kode1);
        harga.setText(harga1);
    }//GEN-LAST:event_barangActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void hitungtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungtotalActionPerformed
        // TODO add your handling code here:
        int jumlah1 = Integer.parseInt(jumlah.getText());
        int harga1 = Integer.parseInt(harga.getText());
        int bayar = harga1 * jumlah1;

        total.setText(Integer.toString(bayar));
    }//GEN-LAST:event_hitungtotalActionPerformed

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tabeltransaksi.rowAtPoint(evt.getPoint());
        String barang1 = tabeltransaksi.getValueAt(baris, 0).toString();
        barang.setSelectedItem(barang1);

        String kode1 = tabeltransaksi.getValueAt(baris, 1).toString();
        kode.setText(kode1);

        String harga1 = tabeltransaksi.getValueAt(baris, 2).toString();
        harga.setText(harga1);

        String jumlahbeli = tabeltransaksi.getValueAt(baris, 3).toString();
        jumlah.setText(jumlahbeli);

        String total1 = tabeltransaksi.getValueAt(baris, 4).toString();
        total.setText(total1);

        String tunai1 = tabeltransaksi.getValueAt(baris, 5).toString();
        tunai.setText(tunai1);

        String kembalian1 = tabeltransaksi.getValueAt(baris, 6).toString();
        kembalian.setText(kembalian1);
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try{
            java.sql.Connection conn=koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("DELETE FROM koneksimodul5 WHERE barang='" + barang.getSelectedItem() + 
                    "' AND jumlah='" + jumlah.getText() + "' AND tunai=" + tunai.getText());
            JOptionPane.showMessageDialog(this, "data berhasil dihapus");
            tampildata();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "data gagal dihapus" + e.getMessage());
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tampildata(){
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("barang");
        tbl.addColumn("kode");
        tbl.addColumn("harga");
        tbl.addColumn("jumlah");
        tbl.addColumn("total");
        tbl.addColumn("tunai");
        tbl.addColumn("kembalian");
        
        try {
            java.sql.Connection conn = tugas5.koneksi.koneksiDB();
            String sql = "select * from koneksimodul5";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
        
            while (rs.next()) {
                Object[] row = {rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4), 
                    rs.getString(5), rs.getString(6), 
                    rs.getString(7)
                };
                tbl.addRow(row);
            }
            
            tabeltransaksi.setModel(tbl);
            tabel.setModel(tbl);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forminput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> barang;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitungkembali;
    private javax.swing.JButton hitungtotal;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kode;
    private javax.swing.JButton kurangjumlah;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JButton tambahjumlah;
    private javax.swing.JTextField total;
    private javax.swing.JTextField tunai;
    // End of variables declaration//GEN-END:variables
}
